name: package_info_plus_module
description: "JuneFlow Module for package_info_plus."
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/package_info_plus_module

version: 0.0.1+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.0
  june_flow_util:
  package_info_plus: ^6.0.0 #@add

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true