name: package_info_plus_module
description: "this module is a part of the juneflow project, it provides a package_info_plus module for flutter project."
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/package_info_plus_module

version: 1.0.2

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router:
  june_flow_util:
  package_info_plus: #@add

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true